CREATE TABLE tournament_join_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    requester_user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    status VARCHAR(20) NOT NULL,
    player_note VARCHAR(500),
    manager_note VARCHAR(500),
    decided_by_user_id INTEGER REFERENCES users(id),
    requested_at TIMESTAMP NOT NULL,
    decided_at TIMESTAMP,
    withdrawn_at TIMESTAMP,
    resubmit_after TIMESTAMP,
    resubmit_unlocked_by_user_id INTEGER REFERENCES users(id),
    resubmit_unlocked_at TIMESTAMP,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT tournament_join_requests_status_check
        CHECK (status IN ('PENDING', 'ACCEPTED', 'REJECTED', 'WITHDRAWN', 'EXPIRED')),
    CONSTRAINT tournament_join_requests_player_note_length_check
        CHECK (player_note IS NULL OR length(player_note) <= 500),
    CONSTRAINT tournament_join_requests_manager_note_length_check
        CHECK (manager_note IS NULL OR length(manager_note) <= 500),
    CONSTRAINT tournament_join_requests_tournament_player_uidx
        UNIQUE (tournament_id, player_id)
);

CREATE INDEX tournament_join_requests_tournament_status_idx
    ON tournament_join_requests (tournament_id, status);

CREATE INDEX tournament_join_requests_requester_status_idx
    ON tournament_join_requests (requester_user_id, status);
