-- Inquiries from clubs that want to join the platform. Clubs are provisioned
-- manually by the platform operator; this table stores the contact-form
-- submissions the operator reviews before creating the club account.
CREATE TABLE club_contact_requests (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    club_name VARCHAR(255) NOT NULL,
    contact_name VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    message TEXT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
