-- Elo-style player ratings.
-- `players` gains a live rating plus the counters the rating engine needs; a
-- separate append-only `rating_events` log records every rating change so the
-- history can be audited and (later) replayed. Guests (external players) keep
-- the default rating and never receive rating_events.

ALTER TABLE players ADD COLUMN rating INTEGER NOT NULL DEFAULT 1000;
ALTER TABLE players ADD COLUMN rated_matches INTEGER NOT NULL DEFAULT 0;
ALTER TABLE players ADD COLUMN last_rated_at TIMESTAMP;

CREATE TABLE rating_events (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    player_id INTEGER NOT NULL REFERENCES players(id),
    match_id INTEGER REFERENCES matches(id),
    tournament_id INTEGER REFERENCES tournaments(id),
    reason VARCHAR(20) NOT NULL,
    delta INTEGER NOT NULL,
    rating_after INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT rating_events_reason_check CHECK (reason IN ('MATCH', 'GUEST_WIN', 'GUEST_LOSS', 'TOURNAMENT_BONUS', 'DECAY'))
);

CREATE INDEX idx_rating_events_player_created_at ON rating_events(player_id, created_at);
