-- Baseline schema for TennisTournamentBackend.
-- This migration is the source of truth for new environments (including Supabase).

CREATE TABLE users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255) UNIQUE,
    auth_provider VARCHAR(50) NOT NULL DEFAULT 'clerk',
    auth_subject VARCHAR(255) UNIQUE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE players (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER UNIQUE REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    external BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE clubs (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER NOT NULL REFERENCES users(id),
    name VARCHAR(255) NOT NULL,
    phone_number VARCHAR(20),
    address TEXT
);

CREATE TABLE club_admins (
    club_id INTEGER NOT NULL REFERENCES clubs(id),
    user_id INTEGER NOT NULL REFERENCES users(id),
    CONSTRAINT PK_club_admins PRIMARY KEY (club_id, user_id)
);

CREATE TABLE tournaments (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    surface VARCHAR(50),
    club_id INTEGER NOT NULL REFERENCES clubs(id),
    start_date TIMESTAMP NOT NULL,
    end_date TIMESTAMP NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT tournaments_surface_check CHECK (surface IN ('CLAY', 'HARD', 'GRASS') OR surface IS NULL)
);

CREATE TABLE tournament_players (
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id),
    player_id INTEGER NOT NULL REFERENCES players(id),
    CONSTRAINT tournament_players_pkey PRIMARY KEY (player_id, tournament_id)
);

CREATE TABLE tournament_phases (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tournament_id INTEGER NOT NULL REFERENCES tournaments(id) ON DELETE CASCADE,
    phase_order INTEGER NOT NULL,
    format VARCHAR(20) NOT NULL,
    rounds INTEGER NOT NULL,
    configuration JSONB NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT tournament_phases_phase_order_check CHECK (phase_order > 0),
    CONSTRAINT tournament_phases_rounds_check CHECK (rounds > 0),
    CONSTRAINT tournament_phases_format_check CHECK (format IN ('KNOCKOUT', 'GROUP', 'SWISS'))
);

CREATE TABLE groups (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id INTEGER NOT NULL REFERENCES tournament_phases(id),
    name VARCHAR(10) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP
);

CREATE TABLE group_standings (
    group_id INTEGER NOT NULL REFERENCES groups(id) ON DELETE CASCADE,
    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    matches_played INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    points INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT group_standings_pkey PRIMARY KEY (group_id, player_id)
);

CREATE TABLE swiss_rankings (
    phase_id INTEGER NOT NULL REFERENCES tournament_phases(id) ON DELETE CASCADE,
    player_id INTEGER NOT NULL REFERENCES players(id) ON DELETE CASCADE,
    round INTEGER NOT NULL,
    points INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT PK_Swiss_Rankings PRIMARY KEY (phase_id, player_id, round)
);

CREATE TABLE matches (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phase_id INTEGER NOT NULL REFERENCES tournament_phases(id) ON DELETE CASCADE,
    round INTEGER NOT NULL,
    group_id INTEGER REFERENCES groups(id) ON DELETE CASCADE,
    player1_id INTEGER REFERENCES players(id),
    player2_id INTEGER REFERENCES players(id),
    winner_id INTEGER REFERENCES players(id),
    score JSONB,
    status VARCHAR(20) NOT NULL DEFAULT 'SCHEDULED',
    scheduled_time TIMESTAMP,
    court VARCHAR(100),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP,
    CONSTRAINT matches_round_check CHECK (round > 0),
    CONSTRAINT matches_status_check CHECK (status IN ('SCHEDULED', 'LIVE', 'COMPLETED', 'WALKOVER'))
);

CREATE TABLE match_dependencies (
    match_id INTEGER NOT NULL REFERENCES matches(id),
    required_match_id INTEGER NOT NULL REFERENCES matches(id),
    required_outcome VARCHAR(20) NOT NULL,
    CONSTRAINT match_dependencies_pkey PRIMARY KEY (match_id, required_match_id),
    CONSTRAINT match_dependencies_required_outcome_check CHECK (required_outcome IN ('WINNER', 'LOSER'))
);
