CREATE TABLE IF NOT EXISTS achievements (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    key VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    description TEXT,
    rule_type VARCHAR(100) NOT NULL,
    threshold INTEGER NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT achievements_rule_type_check CHECK (
        rule_type IN ('TOURNAMENT_WINS_AT_LEAST', 'MATCH_WINS_AT_LEAST', 'MATCHES_PLAYED_AT_LEAST')
    ),
    CONSTRAINT achievements_threshold_positive_check CHECK (threshold > 0)
);

INSERT INTO achievements (key, name, description, rule_type, threshold, active)
SELECT
    'tournament_winner',
    'Tournament Winner',
    'Awarded for winning at least one tournament.',
    'TOURNAMENT_WINS_AT_LEAST',
    1,
    TRUE
WHERE NOT EXISTS (
    SELECT 1 FROM achievements WHERE key = 'tournament_winner'
);
